//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.30 at 11:00:49 ���� CST 
//


package com.cwms.qm.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deliveryOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="warehouseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logisticsCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deliveryOrders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="deliveryOrder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="deliveryOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="warehouseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="logisticsCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="orderLines">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="orderLine" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="orderLineNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flag",
    "code",
    "message",
    "deliveryOrderId",
    "warehouseCode",
    "logisticsCode",
    "deliveryOrders"
})
@XmlRootElement(name = "response")
public class QmOutboundResponseDto {

    @XmlElement(required = true)
    protected String flag;
    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(required = true)
    protected String deliveryOrderId;
    @XmlElement(required = true)
    protected String warehouseCode;
    @XmlElement(required = true)
    protected String logisticsCode;
    @XmlElement(required = true)
    protected DeliveryOrders deliveryOrders;

    /**
     * Gets the value of the flag property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFlag(String value) {
        this.flag = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the message property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the deliveryOrderId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeliveryOrderId() {
        return deliveryOrderId;
    }

    /**
     * Sets the value of the deliveryOrderId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeliveryOrderId(String value) {
        this.deliveryOrderId = value;
    }

    /**
     * Gets the value of the warehouseCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * Sets the value of the warehouseCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWarehouseCode(String value) {
        this.warehouseCode = value;
    }

    /**
     * Gets the value of the logisticsCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * Sets the value of the logisticsCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLogisticsCode(String value) {
        this.logisticsCode = value;
    }

    /**
     * Gets the value of the deliveryOrders property.
     *
     * @return
     *     possible object is
     *     {@link DeliveryOrders }
     *
     */
    public DeliveryOrders getDeliveryOrders() {
        return deliveryOrders;
    }

    /**
     * Sets the value of the deliveryOrders property.
     *
     * @param value
     *     allowed object is
     *     {@link DeliveryOrders }
     *
     */
    public void setDeliveryOrders(DeliveryOrders value) {
        this.deliveryOrders = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="deliveryOrder">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="deliveryOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="warehouseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="logisticsCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="orderLines">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="orderLine" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="orderLineNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deliveryOrder"
    })
    public static class DeliveryOrders {

        @XmlElement(required = true)
        protected DeliveryOrder deliveryOrder;

        /**
         * Gets the value of the deliveryOrder property.
         *
         * @return
         *     possible object is
         *     {@link DeliveryOrder }
         *
         */
        public DeliveryOrder getDeliveryOrder() {
            return deliveryOrder;
        }

        /**
         * Sets the value of the deliveryOrder property.
         *
         * @param value
         *     allowed object is
         *     {@link DeliveryOrder }
         *
         */
        public void setDeliveryOrder(DeliveryOrder value) {
            this.deliveryOrder = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="deliveryOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="warehouseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="logisticsCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="orderLines">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="orderLine" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="orderLineNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "deliveryOrderId",
            "warehouseCode",
            "logisticsCode",
            "orderLines",
            "createTime"
        })
        public static class DeliveryOrder {

            @XmlElement(required = true)
            protected String deliveryOrderId;
            @XmlElement(required = true)
            protected String warehouseCode;
            @XmlElement(required = true)
            protected String logisticsCode;
            @XmlElement(required = true)
            protected OrderLines orderLines;
            @XmlElement(required = true)
            protected String createTime;

            /**
             * Gets the value of the deliveryOrderId property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDeliveryOrderId() {
                return deliveryOrderId;
            }

            /**
             * Sets the value of the deliveryOrderId property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDeliveryOrderId(String value) {
                this.deliveryOrderId = value;
            }

            /**
             * Gets the value of the warehouseCode property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getWarehouseCode() {
                return warehouseCode;
            }

            /**
             * Sets the value of the warehouseCode property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setWarehouseCode(String value) {
                this.warehouseCode = value;
            }

            /**
             * Gets the value of the logisticsCode property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLogisticsCode() {
                return logisticsCode;
            }

            /**
             * Sets the value of the logisticsCode property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLogisticsCode(String value) {
                this.logisticsCode = value;
            }

            /**
             * Gets the value of the orderLines property.
             *
             * @return
             *     possible object is
             *     {@link OrderLines }
             *
             */
            public OrderLines getOrderLines() {
                return orderLines;
            }

            /**
             * Sets the value of the orderLines property.
             *
             * @param value
             *     allowed object is
             *     {@link OrderLines }
             *
             */
            public void setOrderLines(OrderLines value) {
                this.orderLines = value;
            }

            /**
             * Gets the value of the createTime property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCreateTime() {
                return createTime;
            }

            /**
             * Sets the value of the createTime property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCreateTime(String value) {
                this.createTime = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="orderLine" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="orderLineNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "orderLine"
            })
            public static class OrderLines {

                @XmlElement(required = true)
                protected List<OrderLine> orderLine;

                /**
                 * Gets the value of the orderLine property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the orderLine property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOrderLine().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link OrderLine }
                 *
                 *
                 */
                public List<OrderLine> getOrderLine() {
                    if (orderLine == null) {
                        orderLine = new ArrayList<OrderLine>();
                    }
                    return this.orderLine;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="orderLineNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="itemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "orderLineNo",
                    "itemCode",
                    "itemId",
                    "quantity"
                })
                public static class OrderLine {

                    @XmlElement(required = true)
                    protected String orderLineNo;
                    @XmlElement(required = true)
                    protected String itemCode;
                    @XmlElement(required = true)
                    protected String itemId;
                    @XmlElement(required = true)
                    protected String quantity;

                    /**
                     * Gets the value of the orderLineNo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOrderLineNo() {
                        return orderLineNo;
                    }

                    /**
                     * Sets the value of the orderLineNo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOrderLineNo(String value) {
                        this.orderLineNo = value;
                    }

                    /**
                     * Gets the value of the itemCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getItemCode() {
                        return itemCode;
                    }

                    /**
                     * Sets the value of the itemCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setItemCode(String value) {
                        this.itemCode = value;
                    }

                    /**
                     * Gets the value of the itemId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getItemId() {
                        return itemId;
                    }

                    /**
                     * Sets the value of the itemId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setItemId(String value) {
                        this.itemId = value;
                    }

                    /**
                     * Gets the value of the quantity property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getQuantity() {
                        return quantity;
                    }

                    /**
                     * Sets the value of the quantity property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setQuantity(String value) {
                        this.quantity = value;
                    }

                }

            }

        }

    }

}
